#!/usr/bin/env python3

# general-purpose source runner / builder
#
# supported languages:
#   - C23       -> clang
#   - Python    -> python3
#   - Java      -> javac / java
#
# features:
# - recursively finds source files
# - ambiguous source names are rejected
# - build artifacts are kept under ./build/
# - C libraries under ./lib/c/ are automatically linked
# - C debug/release profiles
# - Java packages are read from package declarations
# - Java package directory structure is validated
# - Java uses ./build/java as its classpath root
# - Java package dependencies are supported
# - subdued runner output, normal program output
# - easy to extend with additional languages
#
# usage:
#   ./run.py <file-name | path>
#   ./run.py <file-name | path> --release


import re
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Callable


# ---------------------------------------------------------------------------
# configuration
# ---------------------------------------------------------------------------

ROOT = Path.cwd()
BUILD_DIR = ROOT / "build"
LIB_DIR = ROOT / "lib"


# ---------------------------------------------------------------------------
# terminal formatting
# ---------------------------------------------------------------------------

# Use terminal dim formatting for messages generated by this runner.
# Disable it when stdout is redirected so escape sequences do not end up
# in redirected output.

if sys.stdout.isatty():
    DIM = "\033[90m"
    RESET = "\033[0m"
else:
    DIM = ""
    RESET = ""


def dim(text: str = "") -> str:
    return f"{DIM}{text}{RESET}"


def print_dim(text: str = "") -> None:
    print(dim(text))


# ---------------------------------------------------------------------------
# utilities
# ---------------------------------------------------------------------------

def die(message: str, code: int = 1) -> None:
    print(f"error: {message}", file=sys.stderr)
    sys.exit(code)


def require_command(command: str) -> None:
    if shutil.which(command) is None:
        die(f"required command not found: {command}")


def run_command(cmd: list[str]) -> int:
    print_dim(" ".join(cmd))
    print_dim()

    return subprocess.run(cmd).returncode


def is_inside(path: Path, directory: Path) -> bool:
    """Return True if path is inside directory."""

    try:
        path.resolve().relative_to(directory.resolve())
        return True
    except ValueError:
        return False


def relative_to_root(path: Path) -> Path:
    """Return a path relative to ROOT with a useful error message."""

    try:
        return path.resolve().relative_to(ROOT.resolve())
    except ValueError:
        die(f"source is outside runner root: {path}")

    raise AssertionError  # unreachable


# ---------------------------------------------------------------------------
# source discovery
# ---------------------------------------------------------------------------

def find_source(query: str) -> Path | None:
    """
    Resolve a source file from either:

        ./path/to/file.c
        path/to/file.c
        file.c
        file

    If a bare filename matches multiple files, fail instead of
    arbitrarily selecting one.
    """

    candidate = Path(query)

    # Explicit path.
    if candidate.exists() and candidate.is_file():
        return candidate.resolve()

    matches: list[Path] = []

    for file in ROOT.rglob("*"):
        if not file.is_file():
            continue

        # Never search generated build artifacts.
        if is_inside(file, BUILD_DIR):
            continue

        # Never search hidden VCS metadata.
        if any(part.startswith(".") for part in file.relative_to(ROOT).parts):
            continue

        if file.name == query or file.stem == query:
            matches.append(file.resolve())

    if not matches:
        return None

    if len(matches) > 1:
        print(
            f"error: multiple source files match '{query}':",
            file=sys.stderr,
        )

        for match in sorted(matches):
            print(
                f"  {match.relative_to(ROOT)}",
                file=sys.stderr,
            )

        print(
            "\nuse an explicit path to select one.",
            file=sys.stderr,
        )

        sys.exit(1)

    return matches[0]


# ---------------------------------------------------------------------------
# build paths / output
# ---------------------------------------------------------------------------

def print_build_info(
    src: Path,
    language: str,
    output: Path | None,
) -> None:
    print_dim()
    print_dim("building:")
    print_dim(f"  language : {language}")
    print_dim(f"  source   : {src}")

    if output is not None:
        print_dim(f"  output   : {output}")

    print_dim()


def source_build_dir(src: Path, language: str) -> Path:
    """
    Return a build directory corresponding to a source file.

    The source path relative to ROOT is preserved underneath the
    language-specific build directory.

    Example:

        college/foo/main.c
        -> build/c/college/foo/

        college/foo/main.py
        -> build/python/college/foo/
    """

    relative = relative_to_root(src)

    return BUILD_DIR / language / relative.parent


# ---------------------------------------------------------------------------
# Java helpers
# ---------------------------------------------------------------------------

JAVA_IDENTIFIER = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
JAVA_PACKAGE_RE = re.compile(
    r"^\s*package\s+([A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)*)\s*;",
    re.MULTILINE,
)


def java_package(src: Path) -> str | None:
    """
    Read the Java package declaration from the source file.

    Example:

        package aug26;

        -> "aug26"

        package college.algorithms;

        -> "college.algorithms"

    A missing package declaration means the default package.
    """

    try:
        text = src.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        die(f"could not read Java source as UTF-8: {src}")

    match = JAVA_PACKAGE_RE.search(text)

    if match is None:
        return None

    return match.group(1)


def java_package_parts(src: Path) -> tuple[str, ...]:
    """Return the package as individual path components."""

    package = java_package(src)

    if package is None:
        return ()

    return tuple(package.split("."))


def java_source_root(src: Path) -> Path:
    """
    Determine the Java source root from the package declaration.

    Example:

        college/593-PCC-ICB/aug26/Grader.java
        package aug26;

        -> college/593-PCC-ICB

    For:

        college/593-PCC-ICB/aug26/math/Grader.java
        package aug26.math;

        -> college/593-PCC-ICB
    """

    package_parts = java_package_parts(src)

    if not package_parts:
        # A default-package Java file has no package hierarchy to strip.
        return src.parent

    source_root = src.parent

    for _ in package_parts:
        source_root = source_root.parent

    return source_root


def validate_java_package(src: Path) -> None:
    """
    Validate that the Java package declaration matches the directory
    structure.

    Example:

        aug26/Grader.java
        package aug26;

        is valid.

    But:

        aug19/Grader.java
        package aug26;

        is rejected.
    """

    package_parts = java_package_parts(src)

    if not package_parts:
        return

    relative = relative_to_root(src)

    if len(relative.parts) < len(package_parts) + 1:
        die(
            f"Java source path is too short for package "
            f"'{java_package(src)}': {src}"
        )

    actual_parts = relative.parts[-(len(package_parts) + 1):-1]

    if tuple(actual_parts) != package_parts:
        expected = "/".join(package_parts)

        actual = "/".join(actual_parts)

        die(
            f"Java package/path mismatch:\n"
            f"  package declaration : {java_package(src)}\n"
            f"  source directory    : {actual or '(root)'}\n"
            f"  expected directory  : {expected}\n"
            f"  source              : {src}"
        )


def java_class_name(src: Path) -> str:
    """
    Return the fully-qualified Java class name.

    Example:

        package aug26;
        Grader.java

        -> aug26.Grader

    A default-package class is returned simply as:

        Grader
    """

    package = java_package(src)

    if package:
        return f"{package}.{src.stem}"

    return src.stem


def java_package_dir(src: Path) -> Path:
    """
    Return the directory corresponding to the source's Java package.
    """

    package = java_package(src)

    if package is None:
        return src.parent

    return src.parent


def java_sources_in_package(src: Path) -> list[Path]:
    """
    Return all Java source files belonging to the same package directory.

    This allows programs consisting of multiple Java classes to be compiled
    together.

    Example:

        aug19/
            Student.java
            StudentData.java
            Main.java

    Selecting Main.java compiles all three files in that package.
    """

    package_dir = java_package_dir(src)

    package = java_package(src)

    sources: list[Path] = []

    for file in sorted(package_dir.glob("*.java")):
        if not file.is_file():
            continue

        if java_package(file) != package:
            continue

        sources.append(file)

    if src not in sources:
        sources.append(src)

    return sorted(set(sources))


# ---------------------------------------------------------------------------
# language configuration
# ---------------------------------------------------------------------------

@dataclass
class Language:
    extensions: tuple[str, ...]
    build: Callable[[Path, Path], Path | None]
    run: Callable[[Path, Path | None], list[str]]
    command: str


# ---------------------------------------------------------------------------
# C
# ---------------------------------------------------------------------------

C_WARNINGS = [
    "-Wall",
    "-Wextra",
    "-Wpedantic",
    "-Wshadow",
    "-Wconversion",
    "-Wdouble-promotion",
    "-Wformat=2",
    "-Wnull-dereference",
    "-Wimplicit-fallthrough",
    "-Wcast-align",
    "-Winvalid-pch",
    "-Wmissing-declarations",
    "-Wundef",
    "-Wfloat-equal",
]

C_DEBUG_FLAGS = [
    "-g3",
    "-O0",
    "-fsanitize=address,undefined",
    "-fno-omit-frame-pointer",
]

C_RELEASE_FLAGS = [
    "-O2",
]


def build_c(src: Path, build_dir: Path) -> Path:
    require_command("clang")

    output_dir = source_build_dir(src, "c")
    output_dir.mkdir(parents=True, exist_ok=True)

    output = output_dir / src.stem

    if sys.platform == "win32":
        output = output.with_suffix(".exe")

    # Project C libraries.
    lib_dir = LIB_DIR / "c"

    lib_sources: list[str] = []

    if lib_dir.exists():
        lib_sources = [
            str(file)
            for file in sorted(lib_dir.rglob("*.c"))
            if file.resolve() != src.resolve()
        ]

    profile = "release" if "--release" in sys.argv else "debug"

    flags = [
        "-std=c23",
        *C_WARNINGS,
        *(C_RELEASE_FLAGS if profile == "release" else C_DEBUG_FLAGS),
        "-I.",
    ]

    cmd = [
        "clang",
        str(src),
        *lib_sources,
        *flags,
        "-o",
        str(output),
    ]

    print_build_info(src, "C23", output)

    result = run_command(cmd)

    if result != 0:
        sys.exit(result)

    print_dim(f"build successful ({profile}).")
    print_dim()

    return output


def run_c(src: Path, output: Path | None) -> list[str]:
    if output is None:
        die("C build produced no executable")

    return [str(output)]


# ---------------------------------------------------------------------------
# Python
# ---------------------------------------------------------------------------

def build_python(src: Path, build_dir: Path) -> None:
    """
    Python does not need a build step.
    """

    require_command("python3")

    print_build_info(src, "Python", None)
    print_dim("no build step required.")
    print_dim()

    return None


def run_python(src: Path, output: Path | None) -> list[str]:
    return ["python3", str(src)]


# ---------------------------------------------------------------------------
# Java
# ---------------------------------------------------------------------------

def build_java(src: Path, build_dir: Path) -> Path:
    require_command("javac")

    validate_java_package(src)

    # Keep one Java classpath root.
    #
    # javac creates:
    #
    #   build/java/aug26/Grader.class
    #
    # for:
    #
    #   package aug26;
    #
    output_dir = BUILD_DIR / "java"
    output_dir.mkdir(parents=True, exist_ok=True)

    source_root = java_source_root(src)

    package_sources = java_sources_in_package(src)

    # Compile all classes in the selected package together.
    #
    # -sourcepath additionally allows javac to locate imported Java sources
    # elsewhere in the project source tree.
    cmd = [
        "javac",
        "-Xlint:all",
        "-g",
        "-sourcepath",
        str(source_root),
        "-d",
        str(output_dir),
        *[str(source) for source in package_sources],
    ]

    print_build_info(src, "Java", output_dir)

    if len(package_sources) > 1:
        print_dim("sources   :")
        for source in package_sources:
            print_dim(f"  {source}")
        print_dim()

    result = run_command(cmd)

    if result != 0:
        sys.exit(result)

    print_dim("build successful.")
    print_dim()

    return output_dir


def run_java(src: Path, output: Path | None) -> list[str]:
    if output is None:
        die("Java build produced no output directory")

    require_command("java")

    validate_java_package(src)

    class_name = java_class_name(src)

    return [
        "java",
        "-cp",
        str(output),
        class_name,
    ]


# ---------------------------------------------------------------------------
# language registry
# ---------------------------------------------------------------------------

LANGUAGES: dict[str, Language] = {
    "c": Language(
        extensions=(".c",),
        build=build_c,
        run=run_c,
        command="clang",
    ),

    "python": Language(
        extensions=(".py",),
        build=build_python,
        run=run_python,
        command="python3",
    ),

    "java": Language(
        extensions=(".java",),
        build=build_java,
        run=run_java,
        command="javac",
    ),
}


# ---------------------------------------------------------------------------
# language detection
# ---------------------------------------------------------------------------

def detect_language(src: Path) -> tuple[str, Language]:
    extension = src.suffix.lower()

    for name, language in LANGUAGES.items():
        if extension in language.extensions:
            return name, language

    supported = ", ".join(
        extension
        for language in LANGUAGES.values()
        for extension in language.extensions
    )

    die(
        f"unsupported source extension: {extension or '(none)'}\n"
        f"supported extensions: {supported}"
    )

    raise AssertionError  # unreachable


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def main() -> None:
    if len(sys.argv) < 2:
        print_dim("usage: ./run.py <file-name | path> [--release]")
        sys.exit(1)

    query = sys.argv[1]

    src = find_source(query)

    if src is None:
        die(f"source file not found: {query}")

    language_name, language = detect_language(src)

    output = language.build(src, BUILD_DIR)

    command = language.run(src, output)

    print_dim("running:")
    print_dim(" ".join(command))
    print_dim()

    # Do not capture or modify stdout/stderr here.
    # The program inherits the terminal directly and therefore controls
    # its own colors, brightness, formatting, etc.
    result = subprocess.run(command)

    sys.exit(result.returncode)


if __name__ == "__main__":
    main()
