#!/usr/bin/env python3

# general-purpose source runner / builder
#
# supported languages:
#   - C23       -> clang
#   - Python    -> python3
#   - Java      -> javac / java
#
# features:
# - recursively finds source files
# - language-specific build directories
# - language-specific build/run logic
# - C libraries under ./lib/c/ are automatically linked
# - C debug/release profiles
# - subdued runner output, normal program output
# - easy to extend with additional languages
#
# usage:
#   ./run.py <file-name | path>
#   ./run.py <file-name | path> --release

import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Callable


# ---------------------------------------------------------------------------
# configuration
# ---------------------------------------------------------------------------

ROOT = Path.cwd()
BUILD_DIR = ROOT / "build"
LIB_DIR = ROOT / "lib"


# ---------------------------------------------------------------------------
# terminal formatting
# ---------------------------------------------------------------------------

# Use terminal dim formatting for messages generated by this runner.
# Disable it when stdout is redirected so escape sequences do not end up
# in redirected output.
if sys.stdout.isatty():
	DIM = "\033[90m"
	RESET = "\033[0m"
else:
	DIM = ""
	RESET = ""


def dim(text: str = "") -> str:
	return f"{DIM}{text}{RESET}"


def print_dim(text: str = "") -> None:
	print(dim(text))


# ---------------------------------------------------------------------------
# utilities
# ---------------------------------------------------------------------------

def die(message: str, code: int = 1) -> None:
	print(f"error: {message}", file=sys.stderr)
	sys.exit(code)


def require_command(command: str) -> None:
	if shutil.which(command) is None:
		die(f"required command not found: {command}")


def run_command(cmd: list[str]) -> int:
	print_dim(" ".join(cmd))
	print_dim()

	return subprocess.run(cmd).returncode


def find_source(query: str) -> Path | None:
	"""
	Resolve a source file from either:
		./path/to/file.c
		file.c
		file
	"""

	candidate = Path(query)

	# Explicit path
	if candidate.exists() and candidate.is_file():
		return candidate.resolve()

	# Search recursively
	for file in ROOT.rglob("*"):
		if not file.is_file():
			continue

		if file.name == query:
			return file.resolve()

		if file.stem == query:
			return file.resolve()

	return None


def print_build_info(src: Path, language: str, output: Path | None) -> None:
	print_dim()
	print_dim("building:")
	print_dim(f"  language : {language}")
	print_dim(f"  source   : {src}")

	if output is not None:
		print_dim(f"  output   : {output}")

	print_dim()


# ---------------------------------------------------------------------------
# language configuration
# ---------------------------------------------------------------------------

@dataclass
class Language:
	extensions: tuple[str, ...]
	build: Callable[[Path, Path], Path | None]
	run: Callable[[Path, Path | None], list[str]]
	command: str


# ---------------------------------------------------------------------------
# C
# ---------------------------------------------------------------------------

C_WARNINGS = [
	"-Wall",
	"-Wextra",
	"-Wpedantic",
	"-Wshadow",
	"-Wconversion",
	"-Wdouble-promotion",
	"-Wformat=2",
	"-Wnull-dereference",
	"-Wimplicit-fallthrough",
	"-Wcast-align",
	"-Winvalid-pch",
	"-Wmissing-declarations",
	"-Wundef",
	"-Wfloat-equal",
]

C_DEBUG_FLAGS = [
	"-g3",
	"-O0",
	"-fsanitize=address,undefined",
	"-fno-omit-frame-pointer",
]

C_RELEASE_FLAGS = [
	"-O2",
]


def build_c(src: Path, build_dir: Path) -> Path:
	require_command("clang")

	output_dir = build_dir / "c"
	output_dir.mkdir(parents=True, exist_ok=True)

	output = output_dir / src.stem

	if sys.platform == "win32":
		output = output.with_suffix(".exe")

	# Project C libraries
	lib_dir = LIB_DIR / "c"

	lib_sources: list[str] = []

	if lib_dir.exists():
		lib_sources = [
			str(file)
			for file in lib_dir.rglob("*.c")
			if file.resolve() != src.resolve()
		]

	profile = "release" if "--release" in sys.argv else "debug"

	flags = [
		"-std=c23",
		*C_WARNINGS,
		*(C_RELEASE_FLAGS if profile == "release" else C_DEBUG_FLAGS),
		"-I.",
	]

	cmd = [
		"clang",
		str(src),
		*lib_sources,
		*flags,
		"-o",
		str(output),
	]

	print_build_info(src, "C23", output)

	result = run_command(cmd)

	if result != 0:
		sys.exit(result)

	print_dim(f"build successful ({profile}).")
	print_dim()

	return output


def run_c(src: Path, output: Path | None) -> list[str]:
	if output is None:
		die("C build produced no executable")

	return [str(output)]


# ---------------------------------------------------------------------------
# Python
# ---------------------------------------------------------------------------

def build_python(src: Path, build_dir: Path) -> None:
	"""
	Python does not need a build step.

	Returning None means there is no generated executable/artifact.
	"""

	require_command("python3")

	print_build_info(src, "Python", None)
	print_dim("no build step required.")
	print_dim()

	return None


def run_python(src: Path, output: Path | None) -> list[str]:
	return ["python3", str(src)]


# ---------------------------------------------------------------------------
# Java
# ---------------------------------------------------------------------------

def build_java(src: Path, build_dir: Path) -> Path:
	require_command("javac")

	output_dir = build_dir / "java"
	output_dir.mkdir(parents=True, exist_ok=True)

	# javac writes .class files into this directory.
	cmd = [
		"javac",
		"-Xlint:all",
		"-g",
		"-d",
		str(output_dir),
		str(src),
	]

	print_build_info(src, "Java", output_dir)

	result = run_command(cmd)

	if result != 0:
		sys.exit(result)

	print_dim("build successful.")
	print_dim()

	return output_dir


def run_java(src: Path, output: Path | None) -> list[str]:
	if output is None:
		die("Java build produced no output directory")

	require_command("java")

	# Java expects the class name rather than the .java filename.
	class_name = src.stem

	return [
		"java",
		"-cp",
		str(output),
		class_name,
	]


# ---------------------------------------------------------------------------
# language registry
# ---------------------------------------------------------------------------

LANGUAGES: dict[str, Language] = {
	"c": Language(
		extensions=(".c",),
		build=build_c,
		run=run_c,
		command="clang",
	),

	"python": Language(
		extensions=(".py",),
		build=build_python,
		run=run_python,
		command="python3",
	),

	"java": Language(
		extensions=(".java",),
		build=build_java,
		run=run_java,
		command="javac",
	),
}


# ---------------------------------------------------------------------------
# language detection
# ---------------------------------------------------------------------------

def detect_language(src: Path) -> tuple[str, Language]:
	extension = src.suffix.lower()

	for name, language in LANGUAGES.items():
		if extension in language.extensions:
			return name, language

	supported = ", ".join(
		extension
		for language in LANGUAGES.values()
		for extension in language.extensions
	)

	die(
		f"unsupported source extension: {extension or '(none)'}\n"
		f"supported extensions: {supported}"
	)

	raise AssertionError  # unreachable


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def main() -> None:
	if len(sys.argv) < 2:
		print_dim("usage: ./run.py <file-name | path> [--release]")
		sys.exit(1)

	query = sys.argv[1]

	src = find_source(query)

	if src is None:
		die(f"source file not found: {query}")

	language_name, language = detect_language(src)

	build_dir = BUILD_DIR

	output = language.build(src, build_dir)

	command = language.run(src, output)

	print_dim("running:")
	print_dim(" ".join(command))
	print_dim()

	# Do not capture or modify stdout/stderr here.
	# The program inherits the terminal directly and therefore controls
	# its own colors, brightness, formatting, etc.
	result = subprocess.run(command)

	sys.exit(result.returncode)


if __name__ == "__main__":
	main()
